apiVersion: v1
kind: Secret
metadata:
  name: cacerts
  annotations:
    avp.kubernetes.io/path: paas2-kv/data/{{ .Values.certsPath }}/cacerts
    # avp.kubernetes.io/kv-version: 2
type: Opaque
data:
  ca-cert.pem: <ca-cert>
  ca-key.pem: <ca-key>  
  cert-chain.pem: <cert-chain>
  root-cert.pem: <root-cert>      